// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtqqzoygvpuouwipwgye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0cXF6b3lndnB1b3V3aXB3Z3llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5OTEwNzUsImV4cCI6MjA4NjU2NzA3NX0.9WAdGva5Mz5i54-8Ayhf50vhLJwIG6z9rCyWm_BzzE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});